image: mcr.microsoft.com/dotnet/core/sdk:3.1

stages:
  - build
  - publish

before_script:
  - "dotnet restore"

build:
  stage: build
  script:
    - "dotnet build"

pages:
  stage: deploy
  script:
    - "dotnet publish"
    - mkdir .public
    - cp -r bin/Debug/netstandard2.1/publish/wwwroot/* .public
    - mv .public public
  artifacts:
    paths:
      - public
  only:
    - master
